### ISSUE TITLE
Add docs to describe how to build addon operators

### ISSUE THREAD

**Issue by dholbach** [kubernetes-sigs/cluster-addons#11]
This should ideally cover

- [ ] quick intro: what's an addon operator
- [ ] explaining structure, bare minimum of work
- [ ] links to already existing bits
- [ ] caveats(?)

**Comment by stealthybox** [comment]
- [ ] docs + Makefile using kind to make development easier -- merged to kubebuilder-declarative-pattern
- [ ] docs + U/X for go.mod support

**Comment by dholbach** [comment]
Maybe do after #24?

**Comment by vaibhavk** [comment]
@dholbach Can I take this issue if no one is working on it currently?

**Comment by dholbach** [comment]
@vaibhavk Thanks for reaching out.

I believe this will be worked on as part of #39 or #47 - @stealthybox @justinsb @johnsonj please correct me if I'm wrong.

In any case, any help is appreciated!

**Comment by vaibhavk** [comment]
@dholbach I would be happy to help if this issue is not blocked for GSoC.
