### ISSUE TITLE
CoreDNS Operator: Hash ConfigMap Name for RollingUpgrades

### ISSUE THREAD

**Issue by stealthybox** [kubernetes-sigs/cluster-addons#27]
Feature to consider:

The operator could hash the configMap bytes and then update the name by appending the hash to it. The Deployment would then be updated to reference this new name.
This would allow the Deployment with multiple replicas to undergo a proper (and safe) RollingUpdate. (Changing the value of a ConfigMap is a common source of error for config rollouts)

Currently, we are just changing the value of the configmap and relying on the CoreDNS pods to use the `reload` plugin, but this could be optional.

This mechanism is fully supported by kustomize's [`configMapGenerator`](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md) should we integrate kustomize into the operator.

/kind feature

**Comment by annp1987** [comment]
Hi @stealthybox:
I tried to add configMapGenerator to kustomization.yaml file such as:
```yaml
configMapGenerator:
    - name: coredns
      files:
      - /etc/coredns/Corefile
commonAnnotations:
    configHash: ""
```
But I don't know how to use `kustomize build` command to update manifest (channels/packages/coredns/1.3.1/manifest.yaml). Do you have any idea?

In case, I need to update version of coredns from 1.3.1 to 1.4.0. How should I do it? :-)

Thanks :-)

**Comment by annp1987** [comment]
@stealthybox: ah, I should add kustomization.yaml file to channels/packages/coredns/, right?

**Comment by stealthybox** [comment]
You can add the kustomization.yaml to that directory -- that can work.

You'll need to change the way the manifests are applied inside of the operator code so that they use kustomize to process the YAML files.
@johnsonj and @justinsb wrote that portion.
I believe you need to modify a dependency of the operator.

**Comment by annp1987** [comment]
I appreciated your help on this issue.  Do you think we should change something in https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/addon/pkg/loaders/fs.go#L49 with adding kustomize to process the YAML files or any advice?

**Comment by annp1987** [comment]
Hi @johnsonj,

Thank you so much for your great suggestion. I'm making code following your idea and will push for review soon.

**Comment by nodece** [comment]
Hi guys, I will contribute it in GSCO 2020, Is it a hot update issue? 
Update ConfigMap then  look like coreDNS should can reload get latest config.
is it that so?

**Comment by johnsonj** [comment]
/remove-lifecycle rotten

This issue should now be ready to be fixed via kubernetes/kubebuilder-declarative-pattern#66 - The remaining work should be to update the dependency and replace the (manifest)[https://github.com/kubernetes-sigs/cluster-addons/tree/master/coredns/channels/packages/coredns/1.3.1] with a kustomize manifest

**Comment by rajansandeep** [comment]
I believe this has been done with #50 

/close
