### ISSUE TITLE
CoreDNS Operator: Smoke Tests

### ISSUE THREAD

**Issue by johnsonj** [kubernetes-sigs/cluster-addons#36]
Create an end-to-end smoketest for coredns-operator. The test should run locally by default (via kind or kinder) and support running on a remote kubernetes cluster when provided.

The test should implement and validate the following scenarios:

- Creation  
- Deletion 
- Configuration Change 
- Upgrade the version of CoreDNS 
- Downgrade the version of CoreDNS 

This work will require adding multiple versions to the CoreDNS [version directory](https://github.com/kubernetes-sigs/addon-operators/tree/master/coredns/channels/packages/coredns).

Implementation Nodes:

- The test can be based off the existing dashboard-operator smoketest [[src](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/hack/smoketest.go)]. 
- If there is bandwidth, write a test framework in kubebuilder-declarative-pattern and consume it in the coredns-operator repo.  
    - Roughly: A test framework would perform the execution of the test (eg, install the operator, CRDs), provide a set of common validation functions (eg verifyNoWorkloadsWithLabel) and allow the operator author to pass in their own “[AddonTest](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/hack/smoketest.go#L391)” object.
     - The kubebuilder/controller-runtime folks may be providing something like this (/cc @ecordell)

/cc @annp1987

**Comment by vanou** [comment]
After I finish [this issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65), I'll tackle this.

/assign

**Comment by SomtochiAma** [comment]
Heyy @vanou, Care to release one issue?

**Comment by vanou** [comment]
Sorry. Currently I’m working on #65. So, at this time, I unassign me from this.

/un-assign

**Comment by SomtochiAma** [comment]
/assign

@johnsonj I wanted to start working on the test framework first in kubebuilder-pattern, wdyt?

**Comment by johnsonj** [comment]
SGTM @SomtochiAma !
