### ISSUE TITLE
GSoC Tracking Issue: Package all the things!

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/cluster-addons#39]
(Tracking issue for GSoC proposal)

Now that we're making good progress on the various pieces of machinery and integrations for cluster-addons, it's feasible to start a real effort to create addon operators for the most popular and most interesting cluster addons.  Good candidates would be the addons in the (deprecated) [cluster directory of k/k](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons), the [packaged addons in kops](https://github.com/kubernetes/kops/tree/master/upup/models/cloudup/resources/addons) and the [other addons in kops](https://github.com/kubernetes/kops/tree/master/addons).  Or your favorite addons!

Working through packaging some of these has a lot of intrinsic value, but we also hope to discover areas where there are problems with the tooling and/or with the approach.  Hopefully that will seed further interesting mini-projects which can ideally be solved in collaboration with the community, ranging from docs fixes to deeper technical fixes in the machinery.

Some likely areas of investigation:

* How should we package and distribute the base yaml files - e.g. the [manifest bundle proposal](https://github.com/kubernetes/enhancements/pull/1481)
* Can we streamline the process further for simple / generic addons?  Do they need their own controller?
* Can we address the lack of granularity of RBAC?
* What is the best UX for consuming addons in cluster management tooling?
* What information do we need on the cluster? (e.g. [addon discovery](https://github.com/kubernetes-sigs/cluster-addons/pull/37) )

The addons you build will likely end up being used on every kubernetes cluster!  kubeadm and kops are actively working on supporting these operators, and Redhat is also contributing with their background from the Operator SDK / CoreOS / OpenShift.

Proposed mentors: @justinsb and @stealthybox

**Comment by rajansandeep** [comment]
One specific cluster-addon we can focus on is to add enhancements/help needed for the coredns addon operator.
I can mentor in this area as well as any other help that will be needed during the GSoC project

**Comment by rajdas98** [comment]
Hi @justinsb @stealthybox . I have one question. As I can see the add on categories are classified as
- Networking and Network Policy
- Visualization & Control
- Infrastructure ... etc

Can the participant add `new category of addon` ?
Thanks

**Comment by supra08** [comment]
Hi @justinsb, I am looking forward to contribute to cluster-addons in Kubernetes and willing to participate in GSOC 2020. I would really use a help on how to get things started.

**Comment by dholbach** [comment]
The coredns operator GSoC tasks moved to #40.

Another WIP example of [addon operators](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/addons/0035-20190128-addons-via-operators.md) is #35. #34  might be relevant too.

**Comment by Raman-Kumar** [comment]
@dholbach @justinsb 
Can you suggest me some docs or resources to properly understand
 the **_codebase_** of **cluster-addons** and **contributing** to it?

**Comment by dholbach** [comment]
@Raman-Kumar The links in this issue should be a good start.

**Comment by rajdas98** [comment]
Hey @justinsb. Is it necessary to have a BDD while adding add-ons?

**Comment by dholbach** [comment]
/remove-lifecycle stale
/lifecycle active
/assign @SomtochiAma 

With https://github.com/kubernetes/website/pull/23432 landing soon, I think this issue can be closed successfully.

Thanks a lot @SomtochiAma for your fantastic work on this! You really pushed Cluster Addons forward a great deal!

**Comment by dholbach** [comment]
The blog post is out, the project is finished. Thanks again @SomtochiAma !
