### ISSUE TITLE
KubeVirt Addon

### ISSUE THREAD

**Issue by ashleyschuett** [kubernetes-sigs/cluster-addons#61]
## FEATURE REQUEST

Allow users to easily provision a cluster with KubeVirt enabled. This would allow users provisioning there clusters with kubeadm who need to run VMs in containers and easy way to set up their cluster and be able to run their applications from day 1. 

The addon would then deploy the manifest for the kubevirt operator, and then kubevirt CR to deploy the kubevirt components.

**Comment by rajansandeep** [comment]
So I believe that the intention here is to create a KubeVirt-operator here so that it can be deployed as an option when kubeadm, kops etc would adopt it when they adopt using cluster-addons in the future.

/kind feature

**Comment by vanou** [comment]
I would like to work on this.
/assign

**Comment by SomtochiAma** [comment]
@vanou Are you still working on this or should I pick it up?

**Comment by SomtochiAma** [comment]
No problem! I was just checking in. I'll leave it to you

**Comment by vanou** [comment]
Thanks for your kind care : )

**Comment by dholbach** [comment]
Maybe you can collaborate? :-)

**Comment by SomtochiAma** [comment]
That sounds great! @vanou what do you think?

**Comment by dholbach** [comment]
Hey @vanou - thanks for looking into this so far. Maybe you and @SomtochiAma can have a chat on Slack and you can describe what you looked at and agree what needs to be done - maybe review/test each others work. Doing this together is always more fun than doing it alone. :-)

**Comment by vanou** [comment]
Sorry @dholbach for late reply. Today, I'm busy.
OK. I'll contact with @SomtochiAma :)
